import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={`bg-gray-50 ${geistSans.variable} ${geistMono.variable}`}>
        <nav className="w-full bg-white shadow mb-8">
          <div className="max-w-4xl mx-auto px-4 py-3 flex gap-6">
            <Link href="/">Start</Link>
            <Link href="/test">Test</Link>
            <Link href="/auswertung">Auswertung</Link>
            <Link href="/forschung">Forschung</Link>
            <Link href="/impressum">Impressum</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
